# Generated by Django 5.2.8 on 2026-03-30 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_mr', models.CharField(max_length=100, verbose_name='Name (Marathi)')),
                ('name_hi', models.CharField(max_length=100, verbose_name='Name (Hindi)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_mr', models.CharField(max_length=100, verbose_name='Name (Marathi)')),
                ('name_hi', models.CharField(max_length=100, verbose_name='Name (Hindi)')),
                ('slug', models.SlugField(blank=True)),
                ('pin_codes', models.CharField(blank=True, help_text='Comma-separated PIN codes', max_length=500, verbose_name='PIN Codes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name_en'],
                'unique_together': {('district', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_mr', models.CharField(max_length=100, verbose_name='Name (Marathi)')),
                ('name_hi', models.CharField(max_length=100, verbose_name='Name (Hindi)')),
                ('slug', models.SlugField(blank=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, verbose_name='PIN Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='locations.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name_en'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
