# Generated by Django 5.2.8 on 2026-03-30 17:40

import bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(default=bookings.models.generate_booking_id, editable=False, max_length=15, unique=True)),
                ('address_line', models.TextField(verbose_name='Address')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='Landmark')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('VENDOR_ASSIGNED', 'Vendor Assigned'), ('VENDOR_ACCEPTED', 'Vendor Accepted'), ('VENDOR_EN_ROUTE', 'Vendor En Route'), ('IN_PROGRESS', 'In Progress'), ('WORK_COMPLETED', 'Work Completed'), ('CUSTOMER_CONFIRMED', 'Customer Confirmed'), ('INVOICE_GENERATED', 'Invoice Generated'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='REQUESTED', max_length=30, verbose_name='Status')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'Morning (8AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 8PM)')], default='morning', max_length=15, verbose_name='Preferred Time Slot')),
                ('description', models.TextField(verbose_name='Problem Description')),
                ('voice_transcript', models.TextField(blank=True, verbose_name='Voice Transcript')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Base Price')),
                ('spare_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Spare Parts Cost')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Discount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=15, verbose_name='Payment Status')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('wallet', 'Wallet')], default='cod', max_length=10, verbose_name='Payment Method')),
                ('same_professional_requested', models.BooleanField(default=False, verbose_name='Same Professional Requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.area', verbose_name='Area')),
                ('assigned_previous_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Preferred Previous Vendor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceproblem', verbose_name='Service Problem')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='booking_photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=6)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.booking')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Photo',
                'verbose_name_plural': 'Booking Photos',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('quality', 'Quality Issue'), ('delay', 'Delay'), ('behavior', 'Unprofessional Behavior'), ('pricing', 'Pricing Dispute'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('guarantee_claim', models.BooleanField(default=False, verbose_name='7-Day Guarantee Claim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bookings.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review_text', models.TextField(verbose_name='Review')),
                ('vendor_response', models.TextField(blank=True, verbose_name='Vendor Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorETA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_arrival', models.DateTimeField()),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_eta', to='bookings.booking')),
            ],
        ),
    ]
